### ISSUE TITLE
Time series which have unequal lengths

### ISSUE THREAD

**Issue by lijuan123** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#1]
hello, thanks for your perfect job! Could you please give an example for time serises which have unequal lengths?  Thanks you very much

**Comment by White-Link** [comment]
Hi @lijuan123,

Thanks a lot!

Executing the code (for either training or testing) on a dataset having time series of unequal length should be done in exactly the same way as for datasets with all time series of the same length, without changing the execution command. There's a line in the code that checks whether the input dataset has missing values at the end of its time series.

For this to work, data should be given in the [UCR](https://www.cs.ucr.edu/~eamonn/time_series_data_2018/) CSV style (where time series of length shorter than the maximum length in the dataset end with NaN values).

So simply specifying the dataset with the dataset option should work (for instance, for the AllGestureWiimoteX of the UCR archive that has time series of unequal lengths: `--dataset AllGestureWiimoteX`).
