### ISSUE TITLE
Wrong data link in HouseholdPowerConsumption.ipynb (?)

### ISSUE THREAD

**Issue by MrPr3ntice** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#12]
In the example notebook "HouseoldPowerConsumption.ipynb" you wrote:

> The dataset can be found here: https://archive.ics.uci.edu/ml/datasets/ElectricityLoadDiagrams20112014.

This does not seem to be the data you are referring to in your code later (as you use daily windows of length 1440, which suggests a minutely sampling frequency. However, the source mentioned above has a sampling frequency of 15 minutes).

I assume that this source (possibly modified) is meant: https://www.kaggle.com/uciml/electric-power-consumption-data-set

**Comment by White-Link** [comment]
Hi! The link is indeed wrong, thank you for reporting it. The correct link is the following: https://archive.ics.uci.edu/ml/datasets/Individual+household+electric+power+consumption. I will replace it in the notebook.

**Comment by MrPr3ntice** [comment]
Thanks a lot for your fast reply!
