### ISSUE TITLE
How to recover constant length TS training performance with varying length TS.

### ISSUE THREAD

**Issue by AaronSpieler** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#16]
Hello again,

so it turns out the training with varying time series is much slower (as you hinted at in the paper).
So now I'm looking at ways to recover that performance, and wondered whether you have some intuition/preference for the following possibilities.

1) 0 pad all time series 
2) repeat short time series
3) make all time series multivariate
    - `dim0`: the original TS 0 padded
    - `dim1`: 0 if `dim0` is pad otherwise 1

Since the model uses global max pooling all 0 seems a relatively neutral and straight forward "fix".
Of course the choices can be empirically validated, however, maybe you have some intuition/preference or theoretical insight.

Thx in advance!

Best,
Aaron

**Comment by White-Link** [comment]
Hello! Thank you for raising this relevant question that we did not develop in our article.

I think the bottleneck lies in the fact that the representations of the elements of a mini-batch are computed in a sequential manner. If the encoder could be applied to the whole mini-batch in parallel, it would probably improve the efficiency of the procedure.

I would try a solution that does not change the computational graph of the outputted representations. As you proposed, one could pad the time series to the maximum length observed in the mini-batch and apply the causal part of encoder to this padded mini-batch.

Then, the causal nature of the encoder can be leveraged, as its outputs corresponding to the input padded values can be masked when applying the global maximum pooling without impacting the outputs corresponding to the true time series values. This way, the result of the encoding function remains constant with respect to the lengths of the input time series in the mini-batch.

I believe this is a possible solution that maintains the exact training procedure described in the paper. Please let us know whether this solution or the other solutions that you presented alleviate the problem!

**Comment by White-Link** [comment]
Closing this issue for now, please let us know if you have any other question!
