### ISSUE TITLE
out_channels vs reduced_size

### ISSUE THREAD

**Issue by Huilin-Zhu** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#22]
Hi,

In the class CausalCNNEncoder( ), line 207: `linear = torch.nn.Linear(reduced_size, out_channels)`. Before this line, the size of tensor should be (batch_size, out_channels). When passing this tensor to the linear layer `torch.nn.Linear(in_features, out_features, bias=True)`, shouldn't `in_features= out_channels` and `out_features=reduced_size`? So line 207 should be: `linear = torch.nn.Linear(out_channels, reduced_size)`. 

Perhaps I am misinterpreting the meaning of these two variables. Hope you could help me with this question. Thanks in advance!

**Comment by White-Link** [comment]
Hi!  The code is actually written as intended: the output of `CausalCNN` is a time series with a number of channels that is equal to `reduced_size`. The `AdaptiveMaxPool1d` and `SqueezeChannels` layer remove the time variable, leaving a vectorial representation of size `reduced_size`, which is then fed to the linear layer outputting the final vectorial representation of size `out_channels`.

**Comment by Huilin-Zhu** [comment]
Thank you for the reply. But I am still unclear about the output of `CausalCNN`. Sorry for the annoyance if my question is completely off.

The last layer of `CausalCNN` is:
`layers += [CausalConvolutionBlock(channels, out_channels, kernel_size, dilation_size )]`
where `out_channels=320` defined in [default_hyperparameters.json file](https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/blob/d63c42b8b9ecbdf63a4ba8a9336619724a7be054/default_hyperparameters.json).
This indicates that the output of `CausalCNN` = out_channels = 320. Section S2.2 of your paper also stated that: 
> number of output channels of the causal network (before max pooling): 320.

Since `AdaptiveMaxPool1d` and `SqueezeChannels` does not change the length of the time series, so the input to `Linear` should still be 320. But the code states `Linear(reduced_size, out_channels) `, where `reduced_size=160` defined in [default_hyperparameters.json file](https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/blob/d63c42b8b9ecbdf63a4ba8a9336619724a7be054/default_hyperparameters.json). So they don't seem to match?

Thanks again, and looking forward to your answer!

**Comment by White-Link** [comment]
No worries! The issue actually lies in the paper, where we switched by mistake the parameters before pooling (which should be 160) and the size of the final representations (which should be 320). We will point out this problem in this repository, thanks for reporting it!

Regarding the code, it does work as intended. [The `out_channels` variable used in the `CausalCNN` network](https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/blob/master/networks/causal_cnn.py#L171) is actually equal to the `reduced_size` parameter of the config size ([from the constructor of `CausalCNNEncoder`](https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/blob/master/networks/causal_cnn.py#L203)).

So the output of `CausalCNN` has shape `(B, reduced_size, L)` where `B` is the batch size and `L` is the length of the input time series. `AdaptiveMaxPool1d(1)` shrinks the temporal dimension to 1, so its output has shape `(B, reduced_size, 1)`. This does correspond to the input size of the final linear layer, whose output has shape `(B, out_channels)`.

**Comment by Huilin-Zhu** [comment]
Thank you! It is clear now!
