### ISSUE TITLE
Excellent work

### ISSUE THREAD

**Issue by ksachdeva** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#23]
Hi,

I just finished reading your paper and also saw this repository.

This repository is an excellent example of how experiment-driven research should be conducted.

Good paper; very well crafted code; a lot of experiments & datasets; archived resuls. 

Really job well done!

Regards & thanks
Kapil

**Comment by White-Link** [comment]
Hi, thanks a lot for your interest in our work and your kind words - they are appreciated!

Please let us know whether you have any question.

Regards,
Jean-Yves Franceschi
