### ISSUE TITLE
Visualization of classification result

### ISSUE THREAD

**Issue by hyoon970** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#27]
Hello,

I successfully finished to make trained files thanks to your explanation.

I could check the accuracy, however, I don't know how to check the classification result in visualized version

Could you give me some advice about this issue?

Kinds and regards,

Hyoon

**Comment by White-Link** [comment]
Hi, thank you for your interest in our work!

There is no plan to add visualization features for classification results, as this goes beyond the scope of this code, which is to reproduce the result of the corresponding paper. The accuracy is only given through the terminal output and you would need to modify and augment the codebase to add visualization features.

If you have any question regarding the code, please let us know!
