### ISSUE TITLE
About the extraction of positive and negative samples

### ISSUE THREAD

**Issue by xuchunyu123** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#30]
Your paper helped me a lot, but when I was reading the code, I was confused about the choice of positive and negative samples. For one-dimensional time series, representation and positive-representation seem to me to be the same time series selected , the negative samples are ten time series randomly selected from the entire training set. I don’t know if I understand it right. I look forward to your reply.

**Comment by White-Link** [comment]
Hi, sorry for the late answer, and thank your for your interest in our work!

Actually, both in our paper and in our implementation:
 - the negative samples are chosen by first randomly choosing a given number $K$ (typically, 10) of time series in the dataset, and then *extracting random subseries* of these $K$ selected series;
 - the positive sample and the anchor are indeed chosen within the same time series, but *the positive sample is a subseries of the anchor* sampled at random.

In particular, the positive sample and the anchor are different, even though selected in the same time series. You can see in lines 103 and 109 of `losses/triplet_loss.py` that the indices chosen to select the positive sample and the anchor within the same time series differ.

I hope this helps you better understanding our code. feel free to re-open the issue or create another one if you have any other question!

**Comment by xuchunyu123** [comment]
Sorry, I still don't understand, I found that my batch is (batchsize: 10, length: 9931, dimension: 1), for anchor samples and positive samples, only the last index of the batch is different, when I print it out , found that they are all 0, so in the end they are still the same, looking forward to your reply!

**Comment by White-Link** [comment]
Hi, this is strange: on my side I do find by printing variables that positive and anchor samples are different in `losses/triplet_loss.py`.

Could you please detail which variable you are printing, the prompt result, and whether you use a custom dataset?

**Comment by xuchunyu123** [comment]
![image](https://user-images.githubusercontent.com/82310674/193579015-4da575b6-3f28-4db1-96b5-b4c89e60f741.png)
Hello, I printed one of the third index values ​​of one of the anchor samples and the positive sample, and found that they are the same, the input is custom data, and the training set dimension is (3352,9931,1)

**Comment by xuchunyu123** [comment]
Hello, I printed one of the third index values ​​of one of the anchor samples and the positive sample, and found that they are the same, the input is custom data, and the training set dimension is (3352,9931,1)
![image](https://user-images.githubusercontent.com/82310674/193583583-ce5d5493-b0c3-4f89-b7cc-88f29649b892.png)
![image](https://user-images.githubusercontent.com/82310674/193583756-737eded0-e174-45b7-b83e-844445579d6b.png)

**Comment by White-Link** [comment]
Alright, I understand better! Your training set has the wrong shape: it should be of the form `batch, dimension, length`, whereas yours is `batch, length, dimension`. This would explain why the chosen length is always 1, and why anchor and positive samples are the same. Could you confirm that fixing this does solve your issue?

**Comment by xuchunyu123** [comment]
Hold on, I'll try it right away, thanks for your reply, and I'll close this issue if it solves the problem!

**Comment by xuchunyu123** [comment]
Thank you, it worked!

**Comment by White-Link** [comment]
Perfect, let us know if you have any other question!
