### ISSUE TITLE
How to output the results of downstream tasks after each epoch training

### ISSUE THREAD

**Issue by xuchunyu123** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#32]
Because I don’t know how many epochs to set is the best setting and the result is stable, how to change the code so that each epoch outputs the results of downstream tasks?Looking forward to your reply

**Comment by White-Link** [comment]
Hi, you may be interested in [the code for early stopping in the training of the encoder](https://github.com/White-Link/UnsupervisedScalableRepresentationLearningTimeSeries/blob/dcc674541a94ca8a54fbb5503bb75a297a5231cb/scikit_wrappers.py#L271). This was not used to obtain the results reported in the paper but can be used to compute the training performance of the combined encoder and classifier at each epoch.

**Comment by xuchunyu123** [comment]
Hello, I have encountered a new problem. If I want to output the results of the test set for each epoch training, how should I do it?
