### ISSUE TITLE
Each training result on the test set

### ISSUE THREAD

**Issue by xuchunyu123** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#33]
Hello, I have encountered a new problem. If I want to output the results of the test set for each epoch training, how should I do it?

**Comment by White-Link** [comment]
Hi, sorry for the delay! This is not support by our code. For this, you would need to modify the code of the `fit` and `fit_classifier` methods of the class `TimeSeriesEncoderClassifier` to take as input the test set from the main files, with results being computed in `fit_classifier` similarly to the training performance.
