### ISSUE TITLE
I don't know how to compile this code

### ISSUE THREAD

**Issue by happyseone** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#6]
Hi, I want to compile this code but there are few problems with it.

1. When I try to compile 'HouseholdPowerConsumption.ipynb' code,
the error message 'CUDA out of memory' appears. I add torch.cuda.empty_cache() on scikit_wrappers.py. Then the number of epochs is increased a bit, but I still have same error message 'CUDA out of memory'. How can I solve this problem?

2. I tried the usage part, but after the end of epoch, the error message below appears.
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
Epoch:  250
/home/sjkim/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
/home/sjkim/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:823: FutureWarning: The parameter 'iid' is deprecated in 0.22 and will be removed in 0.24.
  "removed in 0.24.", FutureWarning
Traceback (most recent call last):
  File "ucr.py", line 193, in <module>
    os.path.join(args.save_path, args.dataset)
  File "/home/sjkim/work/NIPS2019/scikit_wrappers.py", line 112, in save
    self.save_encoder(prefix_file)
  File "/home/sjkim/work/NIPS2019/scikit_wrappers.py", line 101, in save_encoder
    prefix_file + '_' + self.architecture + '_encoder.pth'
  File "/home/sjkim/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 327, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/sjkim/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/sjkim/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/save/models/Mallat_CausalCNN_encoder.pth'
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
I don't know what to do. Please let me know how to compile the whole code.
Thank you.

**Comment by White-Link** [comment]
Hello,

1. This code was run on a GPU with 16 GB of vRAM; it may be that your GPU does not have enough memory. You could try to lower the value of "nb_random_samples" (K in the paper) to reduce memory usage. Alternatively, I can provide the corresponding pretrained model.

2. Training was successfully completed, but you have to specify a path to save the models. `/path/to/save/models/` is a placeholder that you have to replace with a folder that already exists in your filesystem.

**Comment by happyseone** [comment]
I totally understand the answer to the first question, but I need more answer to second question.

So, you mean that I have to make the folder 'Mallat_CausalCNN_encoder.pth'  in /path/to/save/models/.

The location of ucr.py is currently in NIPS2019 folder. Please consider this.
![20200329_175321](https://user-images.githubusercontent.com/18029954/77845015-4f980100-71e6-11ea-99ab-104366be5d8c.png)

Even though, I have the folder named 'Mallat_CausalCNN_encoder.pth', I can't compile the ucr.py. I got the same error message.
Is Mallat_CausalCNN_encoder.pth not a folder?
I don't understand the format of Mallat_CausalCNN_encoder.pth.
If Mallat_CausalCNN_encoder.pth is a pth file, then how can I make an empty pth file to save Mallat_CausalCNN_encoder.pth?

**Comment by White-Link** [comment]
Sorry if my answer was not clear.

The code is actually trying to save the model as a `pth` file named `Mallat_CausalCNN_encoder.pth` (the name is chosen by the code depending on the data, in this case, Mallat), in the folder that you specify with the option `--save_path`. So you should create this folder yourself, no need to create a blank `pth` file.

In the example of the README file, the placeholder for this folder is `/path/to/save/models`, but you have to specifiy a folder that exists in your filesystem. In your case, you could create a subfolder `models` of `NIPS2019`, and use `--save_path models` if you run the code from `NIPS2019`.

**Comment by happyseone** [comment]
I just get the result of your model. Thank you so much.

By the way, I want to try your model with another time series dataset, not in UCR and UEA repository. So, I make new data in tsv format and run the code.
Then
Traceback (most recent call last):
  File "ucr.py", line 169, in <module>
    args.path, args.dataset
  File "ucr.py", line 56, in load_UCR_dataset
    test_labels = numpy.vectorize(transform.get)(test_array[:, 0])
  File "/home/sjkim/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/sjkim/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2170, in _vectorize_call
    res = array(outputs, copy=False, subok=True, dtype=otypes[0])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

This is the error message.
I run the code 'ucr.py' and the dataset in UCR repository looks like label in the first column and features in the other columns. I did same way but my dataset is not appropriate to run the model. What should I do?

**Comment by White-Link** [comment]
You're welcome!

You are using the right input format, from what I can tell. It may be that a label encountered in your testing data does not exist in the training data, thus cannot be found in the dictionary `transform` that processes labels.

If that is the case, you should create new training and testing data so that all labels are encountered in the training data.

**Comment by happyseone** [comment]
Thank you very much. Your answer was very helpful to me.
I have one last question about the sparse labeling setting. In your paper, you compare your method and ResNet in TwoPatterns dataset. Which part of your code is related to sparse labeling setting?
Thank you a million and have a nice day!

**Comment by happyseone** [comment]
I understood the process. Thank you a million and have a nice day!
