### ISSUE TITLE
The error appears in uea.py ,it has "JavaException: Attribute isn't relation-valued!", but I found all arff files has the same form.

### ISSUE THREAD

**Issue by carinazhang-meng** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#8]
(venv1) D:\Downloads\paper\paper>python uea.py --dataset Mallat --path Mallat1/ --save_path D:/Downloads/paper/UEAmodels --hyper default_hyperparamet ers.json DEBUG:weka.core.jvm:Adding bundled jars DEBUG:weka.core.jvm:Classpath=['D:\\Anaconda\\envs\\venv1\\lib\\site-packages\\javabridge\\jars\\rhino-1.7R4.jar', 'D:\\Anaconda\\envs\\venv1\\lib\\s ite-packages\\javabridge\\jars\\runnablequeue.jar', 'D:\\Anaconda\\envs\\venv1\\lib\\site-packages\\javabridge\\jars\\cpython.jar', 'D:\\Anaconda\\en vs\\venv1\\lib\\site-packages\\weka\\lib\\python-weka-wrapper.jar', 'D:\\Anaconda\\envs\\venv1\\lib\\site-packages\\weka\\lib\\weka.jar'] DEBUG:weka.core.jvm:MaxHeapSize=default DEBUG:weka.core.jvm:Package support disabled WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by weka.core.WekaPackageClassLoaderManager (file:/D:/Anaconda/envs/venv1/Lib/site-packages/weka/lib/weka.jar) to m ethod java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) WARNING: Please consider reporting this to the maintainers of weka.core.WekaPackageClassLoaderManager WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release Exception in thread "Thread-0" java.lang.IllegalArgumentException: Attribute isn't relation-valued!
        at weka.core.AbstractInstance.relationalValue(AbstractInstance.java:621)         at weka.core.AbstractInstance.relationalValue(AbstractInstance.java:598) Traceback (most recent call last):   File "uea.py", line 158, in <module>     args.path, args.dataset   
File "uea.py", line 55, in load_UEA_dataset     nb_dims = train_weka.get_instance(0).get_relational_value(0).num_instances   
File "D:\Anaconda\envs\venv1\lib\site-packages\weka\core\dataset.py", line 704, in get_relational_value     return Instances(javabridge.call(self.jobject, "relationalValue", "(I)Lweka/core/Instances;", index))   
File "D:\Anaconda\envs\venv1\lib\site-packages\javabridge\jutil.py", line 887, in call     result = fn(*nice_args)  
 File "D:\Anaconda\envs\venv1\lib\site-packages\javabridge\jutil.py", line 854, in fn     
raise JavaException(x) javabridge.jutil.JavaException: Attribute isn't relation-valued!

**Comment by White-Link** [comment]
Hello, sorry for the late answer.

I could not reproduce the error you got. Did you install the exact versions of the packages listed in the README.md file (in particular, `python-weka-wrapper3` v0.1.6). ?

Also, I see that you are trying to run `uea.py` on a univariate time series dataset from the UCR repository (Mallat), but `uea.py` does not handle UCR datasets.

**Comment by carinazhang-meng** [comment]
Maybe the reason is the version of python-weka-wrapper3, I ran it in pycharm based Windows. But the codes just weka, I think maybe I need to install the python-weka-wrapper, but I am not sure which version I need to install.

**Comment by White-Link** [comment]
Indeed. My code runs fine when installing `python-weka-wrapper3` v0.1.6 using `pip` (https://pypi.org/project/python-weka-wrapper3/). There may be issues in the installation process, but let me know if you any help!

**Comment by carinazhang-meng** [comment]
Thx。
